version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 338102783115.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"
      - cd DailySharePrice
      - mvn compile
      - mvn package
      - docker build -t dailyshareprice-registry .
      - docker tag dailyshareprice-registry:latest 338102783115.dkr.ecr.us-west-2.amazonaws.com/dailyshareprice-registry:dailyshareprice

  post_build:
    commands:
      - echo "Post_build"
      - docker push 338102783115.dkr.ecr.us-west-2.amazonaws.com/dailyshareprice-registry:dailyshareprice
      - printf '[{"name":"dailyshareprice-container","imageUri":"%s"}]' docker push 338102783115.dkr.ecr.us-west-2.amazonaws.com/dailyshareprice-registry:dailyshareprice > taskdefinition.json
      
artifacts:
  files:
    - DailySharePrice/taskdefinition.json